"""
Supervisor Agent - Plan Review and Quality Control
"""

from langchain_core.messages import SystemMessage

from app.state import AgentState
from app.schema import SupervisorReview
from app.utils.llm import get_supervisor_llm


SUPERVISOR_SYSTEM_PROMPT = """You are a Principal Investigator (PI) reviewing a computational chemistry workflow plan.

Your job is to ensure the plan is:
1. SCIENTIFICALLY SOUND - Operations are in the correct order
2. FEASIBLE - Only uses available tools
3. SAFE - Won't waste compute or cause errors

SCIENTIFIC RULES:
- Structure acquisition (search_mof_db) must happen before operations on structures
- Optimization (optimize_structure_ase) should typically happen before energy calculations
- Energy calculations (calculate_energy_force) should use optimized structures when possible

AVAILABLE TOOLS:
- search_mof_db: Search for MOF structures
- optimize_structure_ase: Optimize geometry
- calculate_energy_force: Calculate energy and forces

REVIEW THE PLAN:
{plan}

Provide your review in the following format:
- approved: true/false
- feedback: Detailed explanation

If approved, say "APPROVED" and explain why the plan is good.
If rejected, explain what's wrong and how to fix it.
"""


def supervisor_node(state: AgentState) -> AgentState:
    """
    Supervisor Agent - Reviews the plan for scientific soundness.

    Uses an LLM to validate the execution plan generated by the Analyzer.
    Checks order of operations, feasibility, and safety.
    """

    plan = state.get("plan", [])

    if not plan:
        # No plan to review, skip
        state["is_plan_approved"] = False
        state["review_feedback"] = "No plan provided"
        return state

    # Create review prompt
    llm = get_supervisor_llm()

    # Use structured output
    structured_llm = llm.with_structured_output(SupervisorReview)

    system_message = SystemMessage(
        content=SUPERVISOR_SYSTEM_PROMPT.format(
            plan="\n".join(f"{i+1}. {step}" for i, step in enumerate(plan))
        )
    )

    # Get review
    review = structured_llm.invoke([system_message])

    # Update state
    state["is_plan_approved"] = review.approved
    state["review_feedback"] = review.feedback

    return state
